server:
  port: 8080

spring:
  datasource:
    name: seckillNew
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计 拦截的filters
      filter: stat
      #mysql驱动
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/seckillNew?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&?zeroDateTimeBehavior=convertToNull
      username: root
      password: 123
      #配置初始化大小
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待时间
      max-wait: 60000
      #间隔多久进行一次检测，关闭空闲连接
      time-between-eviction-runs-millis: 60000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lx.seckill.entity
  configuration:
    # 使用jdbc的getGeneratedKeys 可以获取数据库自增主键值
    use-generated-keys: true
    # 使用列别名替换列名，默认true。如：select name as title from table
    use-column-label: true
    # 开启驼峰命名转换，如：Table(create_time) -> Entity(createTime)。
    #不需要我们关心怎么进行字段匹配，mybatis会自动识别`大写字母与下划线`
    map-underscore-to-camel-case: true

# 打印sql
logging:
  level:
    cn.tycoding.mapper: DEBUG